In [1]:
import pandas as pd
import plotly

df = pd.read_csv("202501_202507_주민등록인구및세대현황_월간.csv", encoding='cp949')
df

,행정구역,2025년01월_총인구수,2025년01월_세대수,2025년01월_세대당 인구,2025년01월_남자 인구수,2025년01월_여자 인구수,2025년01월_남여 비율,2025년02월_총인구수,2025년02월_세대수,2025년02월_세대당 인구,...,2025년06월_세대당 인구,2025년06월_남자 인구수,2025년06월_여자 인구수,2025년06월_남여 비율,2025년07월_총인구수,2025년07월_세대수,2025년07월_세대당 인구,2025년07월_남자 인구수,2025년07월_여자 인구수,2025년07월_남여 비율
0,서울특별시 (1100000000),"9,330,658","4,482,949",2.08,"4,504,432","4,826,226",0.93,"9,334,828","4,492,425",2.08,...,2.07,"4,497,354","4,828,262",0.93,"9,323,492","4,502,552",2.07,"4,495,747","4,827,745",0.93
1,서울특별시 종로구 (1111000000),"138,208","72,156",1.92,"66,514","71,694",0.93,"138,277","72,319",1.91,...,1.90,"66,315","71,700",0.92,"137,857","72,499",1.90,"66,201","71,656",0.92
2,서울특별시 중구 (1114000000),"120,325","64,933",1.85,"57,948","62,377",0.93,"120,119","64,932",1.85,...,1.85,"57,267","61,830",0.93,"118,861","64,369",1.85,"57,098","61,763",0.92
3,서울특별시 용산구 (1117000000),"203,727","103,204",1.97,"97,392","106,335",0.92,"203,550","103,226",1.97,...,1.97,"96,925","106,202",0.91,"202,971","103,274",1.97,"96,826","106,145",0.91
4,서울특별시 성동구 (1120000000),"273,549","131,857",2.07,"132,354","141,195",0.94,"273,577","132,124",2.07,...,2.07,"132,030","141,165",0.94,"272,979","132,160",2.07,"131,952","141,027",0.94
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
287,경상남도 거창군 (4888000000),"59,514","31,098",1.91,"29,241","30,273",0.97,"59,452","31,162",1.91,...,1.90,"29,228","30,132",0.97,"59,268","31,260",1.90,"29,193","30,075",0.97
288,경상남도 합천군 (4889000000),"40,133","23,668",1.70,"19,738","20,395",0.97,"39,938","23,610",1.69,...,1.69,"19,529","20,120",0.97,"39,540","23,479",1.68,"19,470","20,070",0.97
289,제주특별자치도 (5000000000),"669,460","314,683",2.13,"334,794","334,666",1.00,"668,205","314,861",2.12,...,2.12,"333,174","333,451",1.00,"666,226","315,192",2.11,"332,858","333,368",1.00
290,제주특별자치도 제주시 (5011000000),"487,623","225,733",2.16,"243,336","244,287",1.00,"486,762","225,926",2.15,...,2.15,"242,309","243,775",0.99,"485,933","226,374",2.15,"242,145","243,788",0.99
291,제주특별자치도 서귀포시 (5013000000),"181,837","88,950",2.04,"91,458","90,379",1.01,"181,443","88,935",2.04,...,2.03,"90,865","89,676",1.01,"180,293","88,818",2.03,"90,713","89,580",1.01